### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by tobiasmuecksch** [dchester/generator-async#3]
![npm installation error](http://cl.ly/0x3b450l0s1L/Bildschirmfoto%202016-03-25%20um%2010.46.45.png)

Same issue after upgrade to node v5.9.1

**Comment by tobiasmuecksch** [comment]
This might be the reason:
https://www.npmjs.com/package/package-path

![npm info](http://cl.ly/3B1Q1K0T1S15/Bildschirmfoto%202016-03-25%20um%2011.00.57.png)

**Comment by dchester** [comment]
Thanks -- looking better with 2ae834e637d650e9dbd1a6b4fa5952e63b4a994d.
