### ISSUE TITLE
"use strict" bricks the library 

### ISSUE THREAD

**Issue by tobiasmuecksch** [dchester/generator-async#5]
I tried the introductory example like this:

```
var async = require('generator-async');
var fs = async.require('fs');

async.run(function*(){
    "use strict";

    // read a file
    var passwd = yield fs.readFile('/etc/passwd');

    // then read another file
    var group = yield fs.readFile('/etc/group');

    // then spit out the contents of both files
    console.log(passwd, group);
});
```

Results in error: `Error: Attempted to yield bad value: undefined`

I guess the problem is, that fs.readFile() does not return promises.

**Comment by tobiasmuecksch** [comment]
Well that's strange...
Removing `"use strict"` solves the problem. Why is that?

Do you have any explanation? All my projects use `"use strict"`.

**Comment by dchester** [comment]
Thanks -- better with 3a14450e1c3eebbee585f609126d5ab127fdcc18.
