### ISSUE TITLE
async.forEachLimit is not a function

### ISSUE THREAD

**Issue by jots** [dchester/generator-async#7]
Has it not been implemented yet?

``` javascript
async.forEachLimit(data, 1, function*(acct) {
}
TypeError: async.forEachLimit is not a function
```

**Comment by dchester** [comment]
Thanks for pointing that out.  There were actually two issues:
- docs listed the wrong method name -- should be `async.eachLimit`; and
- args weren't quite getting passed through correctly

Should be looking better now in version `0.1.6` which includes 877e43e68cb53cebf6c0d56975bf32afd029c1b0.
